---
name: build-rpms
permissions:
  contents: write
on:
  repository_dispatch:
  workflow_dispatch:

env:
  RPM_NAME: open-vm-tools
  RPM_VERSION: 12.1.5

jobs:
  build-rpms:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build open-vm-tool rpms to local
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          outputs: type=local,dest=artifacts

      - name: Prepare for upload package
        shell: bash
        run: |
          mkdir -p output
          find artifacts -type f -name "${{ env.RPM_NAME }}-${{ env.RPM_VERSION }}*.rpm" -exec mv {} output \;
          cd output
          ls *.rpm | xargs -L1 -I {} sh -c "sha256sum {} > {}.sha256sum"

      - name: Generate release tag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
            echo "release_tag=$(git describe --tags --always) >> $GITHUB_OUTPUT

      - name: Release and upload packages
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: output/*
